#!/usr/bin/env python3
"""Build docs/commands.json (read by the /guide dialog) and docs/COMMANDS.md (the same reference for humans) from

  docs/commands.src.json   curated entries: engine commands, our plugin commands, the `shura` CLI, with English and Russian text
  commands/*.md            our prompt commands: the `description:` in their front matter is the English text (single source),
                           the Russian text comes from the entry with the same id in commands.src.json

    python3 scripts/build_commands.py          # write both files
    python3 scripts/build_commands.py --check  # exit 1 if they are out of date (the tests do this)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "commands.src.json"
CATEGORY_ORDER = ["Help", "Model", "Memory", "Work", "Session", "View", "Input", "Shura (terminal)"]
CATEGORY_RU = {"Help": "Справка", "Model": "Модель", "Memory": "Память", "Work": "Работа", "Session": "Сессии", "View": "Вид",
               "Input": "Ввод", "Shura (terminal)": "Shura (в терминале)"}
SOURCE_NOTE = {"shuracode": ("ShuraCode", "ShuraCode"), "engine": ("engine", "движок"), "shura": ("shura", "shura")}


def front_matter_description(path):
    m = re.match(r"---\n(.*?)\n---", path.read_text(), re.S)
    d = re.search(r"^description:\s*(.+)$", m.group(1), re.M) if m else None
    return d.group(1).strip() if d else None


def build():
    src = json.loads(SRC.read_text())
    by_id = {i["id"]: i for i in src["items"]}
    for md in sorted((ROOT / "commands").glob("*.md")):
        desc = front_matter_description(md)
        item = by_id.get(md.stem)
        if item is None:
            raise SystemExit(f"commands/{md.name} has no entry '{md.stem}' in docs/commands.src.json (add the Russian text there)")
        if desc:
            item["en"] = desc                         # the command file is the source of the English text
    items = list(by_id.values())
    items.sort(key=lambda i: (CATEGORY_ORDER.index(i["category"]), i.get("kind", "slash") != "slash", i["name"].lower()))
    return {"version": src["version"], "items": items}


def markdown(data):
    out = ["# Commands / Команды", "", "Generated by `scripts/build_commands.py` from `docs/commands.src.json` and `commands/*.md`; do not edit by hand. "
           "Inside ShuraCode the same list opens with `/guide`.", ""]
    for cat in CATEGORY_ORDER:
        rows = [i for i in data["items"] if i["category"] == cat]
        if not rows:
            continue
        out += [f"## {cat} / {CATEGORY_RU[cat]}", "", "| Command | What it does | Что делает | Key | From |", "|---|---|---|---|---|"]
        for i in rows:
            only = f" ({', '.join(i['models'])} only)" if i.get("models") else ""
            out.append(f"| `{i['name']}` | {i['en']}{only} | {i['ru']} | {('`' + i['key'] + '`') if i.get('key') else ''} | {SOURCE_NOTE[i['source']][0]} |")
        out.append("")
    return "\n".join(out)


def main(argv):
    data = build()
    files = {ROOT / "docs" / "commands.json": json.dumps(data, ensure_ascii=False, indent=1) + "\n",
             ROOT / "docs" / "COMMANDS.md": markdown(data) + "\n"}
    if "--check" in argv:
        stale = [p.name for p, text in files.items() if not p.exists() or p.read_text() != text]
        if stale:
            print("out of date: " + ", ".join(stale) + " (run scripts/build_commands.py)")
            return 1
        return 0
    for p, text in files.items():
        p.write_text(text)
    print(f"{len(data['items'])} commands -> docs/commands.json, docs/COMMANDS.md")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
